### PR TITLE
Adjusting x-limits for viz.plot_Z_err_cond when plotting the central peak

### PR DESCRIPTION
**Pull request by soosub**
## Context for changes

Adjusting x-limits for viz.plot_Z_err_cond when plotting the central peak

- **Improvements**: 
    * Adjusts _xlim_ in the `viz.plot_Z_err_cond` function to the relevant domain when plotting the central bin for the `viz` module.

Note: this is a small improvement for the viz module (mainly for me to practice with PRs in the FP repo)

## Example usage and tests

- [x] Not Applicable

## Performance results justifying changes

- [x] Not Applicable

## Workflow actions and tests

- [x] Not Applicable

## Expected benefits and drawbacks

**Expected benefits:**
- Less wasted _x-limits_ space when plotting conditional phase probabilities. 

## Related Github issues

- [ ] Not Applicable

## Checklist and integration statements

- [ ] My Python and C++ codes follow this project's coding and commenting styles as indicated by existing files. Precisely, the changes conform to given `black`, `docformatter` and `pylint` configurations. 
- [ ] I have performed a self-review of these changes, and checked my code (including for [codefactor](https://www.codefactor.io/repository/github/xanaduai/flamingpy/branches) compliance), and corrected misspellings to the best of my capacity. I have synced this branch with others as required.
- [ ] I have added context for corresponding changes in documentation and [`README.md`](README.md) as needed.
- [ ] I have added new workflow CI tests for corresponding changes, ensuring codecoverage is 95% or better, and these pass locally for me.
- [ ] I have updated [`CHANGELOG.md`](.github/CHANGELOG.md) following the template. I recognize that the developers may revisit [`CHANGELOG.md`](.github/CHANGELOG.md) and the versioning, and create a Special Release including my changes.

### CODE REVIEW

**Comment by soosub** [comment]
This is a small improvement for the viz module (mainly for me to practice with PRs)

**Comment by sduquemesa** [comment]
Thanks @soosub for this contribution! 

For context, can you add to your PR description or to the discussion two images: one with the older version of the plot and one with your changes applied?

**Comment by soosub** [comment]
> Thanks @soosub for this contribution!
> 
> For context, can you add to your PR description or to the discussion two images: one with the older version of the plot and one with your changes applied?

Before
image

After
image

**Comment by soosub** [comment]
@ilan-tz it's ready! To tackle it I introduced a [`matplotlib.ticker.Formatter`](https://matplotlib.org/stable/api/ticker_api.html) which is a bit more elegant than the previous implementation IMO.

**Review by ilan-tz — CHANGES_REQUESTED** [review]
Nice! I like the move to the Formatter -- didn't know about that before. Let a few comments. Note also one of the pytests (test_pi_string) needs modifying because it doesn't know about the new decimal precision option. Please make sure all pytests pass locally for you

**Comment by sduquemesa** [comment]
Hey @soosub and @ilan-tz, CodeFactor issues are not directly related to this PR. Best is to address those on a different PR.

**Comment by soosub** [comment]
> Hey @soosub and @ilan-tz, CodeFactor issues are not directly related to this PR. Best is to address those on a different PR.

Sure, works for me 😌

**Comment by nariman87** [comment]
Thanks, @soosub. We can skip it for now, but in any future PR, please fill in the description template fully.

**Comment by nariman87** [comment]
@soosub, we also need to sync this with the latest `main`.

**Comment by soosub** [comment]
@nariman87 I just merged the current main. I will also keep the full template in the future 👍🏼

**Review by ilan-tz — APPROVED** [review]

**Pull request merged**
