### PR TITLE
[Discussion] Make noise models immutable

### PR DESCRIPTION
**Pull request by maxtremblay**
## Context for changes

This is a first step toward an immutable API. This immutable API will have many benefits eventually by  

  - Simplifying the implementation of different components of flamingpy in faster lower-level programming languages (C, C++, Rust, Fortran ...)
  - Removing the connection between different components, thus making new algorithms easier to implement. For example, developers won't have to worry about implementation details of noise models and code classes when working on a decoder. 
  - Making it easier to test individual components in isolation.

However, this is a noble goal that we won't reach in a single day. This PR is the first step in that direction. The focus of this PR is to make it such that noise models don't need to update attributes of the surface code class. I am creating the PR sooner than usual to gather comments and feedbacks as soon as possible.

## Tasks

- [x] **Update iid noise to use an immutable API** 

  This first step is the simplest tasks of all. It involves only a few minor modifications of the IidNoise class to make it returns an error as a bit string instead of updating directly the surface code class. However, notice that since I don't want to update anything related to decoders in the PR, I added a new method to the surface code class to apply an error to the node attributes of its egraph. All combined, it looks like this.

```python
code = SurfaceCode(distance=5)

# The noise model only need to know how many qubits there are and nothing more about the code.
# Different noise model may need extra informations. For example,
# a correlated noise model would require information about the qubit adjacency.
# We also provide an error probability of 10%.
noise = IidNoise(len(code), 0.1) 

# We can also provide a seeded rng to make it reproducible.
# Also, that error could be applied to any code (not limited to surface codes)
# as long as it has the correct number of qubits.
# This could be hepful in the future to study different code constructions.
error = noise.sample()

# In the future, the error will be converted directly into a syndrome by the code 
# and then syndrome would be feeded to the decoder. 
# However, to keep the changes manageable, I started by adding this method
# that apply the error directly to code attributes.
code.apply_error(error)

# From there, you can use the usual process to decode the error.
```

- [ ] **When happy with iid noise, do a similar change to CVLayer** 

   One important consideration for CV noise is how to manage homodyne values translation. Do we want to wrap that in a compositor class that will behave like iid noise, do we want to define a more specialized noise model ourself or we want to user to be explicit when using different objects? For the user, here is how the the approachs could look.

### Compositor class

```python
# The sample method of this class should return a sequence of quadratures.
gaussian_noise = GaussianNoise(...) 

# This should have a transform method mapping quadratures to homodyne values.
homodyne_measurement = HomodyneMeasurement(...) 

# This should have a transform method mapping homodynes values to binary error values.
translator = CvTranslator(...) 

# This build the noise model.
# The resulting noise object has a sample method that is similar to one of the iid noise.
noise = compose_noise(gaussian_noise, homodyne_measurement, translator)

# From this point, noise is similar to the previous example.
error = noise.sample()
code.apply_error(error)

# The compose function will look like this. It could also be a stand-alone class.

def compose_noise(*models):
    class Noise:
        def sample(self, rng=np.random.default_rng()):
            error = models[0].sample(rng)
            for model in models[1:]:
                error = model.transform(error)
            return error
    return Noise
```

Notice that there are two building blocks for noise model:
- classes with a sample method
- classes with a transform method

Of course, a class can have both methods, but only classes with the sample method can be used as a final noise model. I feel that this approach is clean, easy to use and allow creation of more complex noise models without too much effort. 

### Specialized class

```python 
# Of course, many class arguments could be optional and we can provide nice defaults.
class CvNoise:
   def __init__(self, grn_arg_1, grn_arg_2, homodyne_arg_1, homodyne_arg_2, translator_arg_1, translator_arg_2):
        ...
       
   def sample(self, rng=np.random.default_rng()):
       gaussian_noise = self.sample_gaussian_noise(rng) 
       homodyne_values = self.generate_homodyne_values(gaussian_noise)
       return self.translator(homodyne_values)
       
    def sample_gaussian_noise(self, rng):
        # do something with self.grn_arg_1 and self.grn_arg_2
    
    def generate_homodyne_values(self, gaussian_noise):
        # do something with self.homodyne_arg_1 and self.homodyne_arg_2 and gaussian_noise
    
    def translate(self, homodyne_values):        
        # do something with self.translator_arg_1 and self.translator_arg_2 and homodyne_values
```

Similar classes could be defined for different noise models, as long as they have a sample method. I prefer the first, but I can see an argument why some users may prefer this one, since all parameters are agglomerated in a single place. Of course, once a class is defined and a noise object is built, we can use it the same way, no matter how it was built.

### Explicit usage

```python
# Similar to the first example, we define building blocks.
gaussian_noise = GaussianNoise(...) 
homodyne_measurement = HomodyneMeasurement(...) 
translator = CvTranslator(...) 

# However, instead of composing the blocks together, we ask the user to explicitly 
# call each object.

quadratures = gaussian_noise.sample()
homodyne_values = homodyne_measurement.generate_homodyne_values(quadratures)
error = translator.translate(homodyne_values)
code.apply_error(error)
```

This approach is similar to the current version of flamingpy. So, it maybe more familiar to current users. However, I believe the first two solutions make it easier to have predefined and optimised functions for Monte Carlo simulations, since they are always the same. As of today, such function would look like this.

```python
def simulate(code, decoder, noise):
   error = noise.sample()
   code.apply_error(error)
   return correct(code, decoder, ...)
```

However, it will change in the future when more progress is done with the API change.

## Checklist and integration statements

*This is for later when we are done*

- [ ] My Python and C++ codes follow the coding and commenting styles of this project as indicated by existing files. Specifically, the changes conform to given `black`, `docformatter` and `pylint` configurations. 
- [ ] I have performed a self-review of these changes, checked my code (including for [codefactor](https://www.codefactor.io/repository/github/xanaduai/flamingpy/branches) compliance), and corrected misspellings to the best of my capacity. I have synced this branch with others as required.
- [ ] I have added context for corresponding changes in documentation and [`README.md`](README.md) as needed.
- [ ] I have added new workflow CI tests for corresponding changes, ensuring codecoverage 95% or better, and these pass locally for me.
- [ ] I have updated [`CHANGELOG.md`](.github/CHANGELOG.md) following the template. I recognize that the developers may revisit [`CHANGELOG.md`](.github/CHANGELOG.md) and the versioning, and create a Special Release including my changes.

### CODE REVIEW

**Comment by nariman87** [comment]
Thanks, @maxtremblay. Overall, great plans for API restructuring as we always want to provide a better modular architecture. I especially like what "Explicit usage" would look like. Let's discuss the details in person.

**Comment by soosub** [comment]
I'm in favour of the Compositor option and the Explicit option which both allow for a neat modular approach IMO. 

I don't know too much about this tbh:

> I believe the first two solutions make it easier to have predefined and optimised functions for Monte Carlo simulations

which might be a plus for the Compositor approach. 

P.S. just for my understanding, would
```
def simulate(code, decoder, noise):
   quadratures = gaussian_noise.sample()
   homodyne_values = homodyne_measurement.generate_homodyne_values(quadratures)
   error = translator.translate(homodyne_values)
   code.apply_error(error)
   return correct(code, decoder, ...)
```
not do exactly the same? Where would the speed-up come from?

**Comment by BestQuark** [comment]
I am in favour of the Compositor class too, it is a very nice idea! I think this is much better since it can not be only limited to integrating CV noise, but also compose different noise models to affect a code with, whereas the other two approaches do not. 

As we discussed in the meeting, one could further define an abstract `NoiseModel` class from which all noise models inherit from. Then, the composer class will take several `NoiseModel` objects and create one effective `NoiseModel` (or Child class) to then generate errors. 
  
> noise = compose_noise(gaussian_noise, homodyne_measurement, translator)

> def compose_noise(*models):
>     class Noise:
>         def sample(self, rng=np.random.default_rng()):
>             error = models[0].sample(rng)
>             for model in models[1:]:
>                 error = model.transform(error)
>             return error
>     return Noise
> ```

**Comment by ilan-tz** [comment]
Thanks for this proposal @maxtremblay ! Based on our discussions I think we are in agreement that we can proceed with the move to immutability. As far as the approach to noise model classes -- a few thoughts:

- I would argue that the current way it's done in FlamingPy is closer to "specialized class" rather than "explicit usage," since most of the work behind-the-scenes is performed by a bunch of methods in, say, `CVLayer`. The translator is the exception, but it may as well be a method of `CVLayer`. 
- I think the idea behind "explicit usage" is to require a knowledgeable user to enumerate the sub-processes of noise application through explicit function calls. However, this has two negative effects: it may alienate less knowledgeable users and make it harder to compose noise models. It doesn't really matter to an expert where to put in the mechanics of the noise model (e.g. in the methods of a class or as separate functions). But the users who want to employ a built-in noise model without getting into the weeds, or make small tweaks to a complex built-in noise model, should be guided via a class template rather than a seemingly random (to a non-expert) combination of functions. Therefore I agree that the "specialized class" or "compositor" options are preferable.
-  The "compositor class" is an interesting idea, but may not work so well in practice. I think there is basically a continuum between the "specialized" and "compositor" solutions, where "compositor" would be advantageous if the noise classes you are composing have the properties that they are _general_ and _independent_. If they are not so general, you will end up making tons of specialized classes anyway, and if they are not independent, your compositor will end up being too complex (and also too specialized), defeating its purpose. In CV land I think you may find that this will be the case, with the only really general and independent class being the translator. 
- Therefore, _I am leaning towards the specialized class_ as our solution here. This would mean that the composition is going to be performed as a method of the class (if I understand correctly), and we will still have opportunity for a common-sense inheritance structure. See, for example, `CVMacroLayer` here: https://github.com/XanaduAI/flamingpy/blob/improve-macro-reduce/flamingpy/noise/cv.py .

@BestQuark @soosub @nariman87 feel free to chime in!

**Comment by maxtremblay** [comment]
> ```
> def simulate(code, decoder, noise):
>    quadratures = gaussian_noise.sample()
>    homodyne_values = homodyne_measurement.generate_homodyne_values(quadratures)
>    error = translator.translate(homodyne_values)
>    code.apply_error(error)
>    return correct(code, decoder, ...)
> ```
> 
> not do exactly the same in the Explicit option case (compared to the Compositor)? Where would the speed-up come from?



My intuition is that if the function is always the same and only calling the sample method of the noise model, we can write it once in cython or something like that and be done with. However, in the explicite case, we would need many such functions. They can be optimized the same, it is just more work.

**Pull request closed without merging**
