### PR TITLE
Rethinking the `dims` parameter in `draw_EGraph`

### LINKED ISSUE #40: Draw method of EGraph does not function without passing `dims` parameter
The draw method of EGraph objects does not function if the EGraph does not have a `dims` parameter defined. It would make sense to either have default dimensions or a way to compute them from the coordinates of the nodes in the graph.

### PR DESCRIPTION
**Pull request by soosub**
## Context for changes

Introduced a more intuitive `dimensions` parameter that could replace the `dims` attribute of the `EGraph` class.

- **Improvements**: 
    * Adjusted the use of `dims` in the `draw_EGraph` method. Introduced a more intuitive `dimensions` parameter that sets the limits of the x, y, and z axes. Now, `dimensions` is a keyword argument of the `draw_EGraph` method, as opposed to being an attribute of the `EGraph` object like `dims`. If `dimensions` is not passed, the axis limits are calculated (smallest rectangle encapsulating the whole graph). Resolves issue #40.
- **Documentation changes**:
    * Added documentation on how the new `dimensions` parameter should be used.

## Example usage and tests

image

image

image

## Expected benefits and drawbacks

**Expected benefits:**
-  Easier and more intuitive way to draw `EGraph` objects. This version no longer requires the `EGraph` to have a `dims` attribute when drawing it.

**Possible drawbacks:**
- The `dims` parameter might be used in other places that I am not aware of. The new `dimensions` parameter might be confusing if this is the case.
- For very large graphs the calculation of the `mins = tuple(map(min, zip(*egraph.nodes)))` and `maxs = tuple(map(max, zip(*egraph.nodes)))` might not be desired. However, I don't think that should be a bottleneck when drawing large graphs.

## Related Github issues
Resolves #40 

## Checklist and integration statements

- [x] My Python and C++ codes follow the coding and commenting styles of this project as indicated by existing files. Specifically, the changes conform to given `black`, `docformatter` and `pylint` configurations. 
- [x] I have performed a self-review of these changes, and checked my code (including for [codefactor](https://www.codefactor.io/repository/github/xanaduai/flamingpy/branches) compliance), and corrected misspellings to the best of my capacity. I have synced this branch with others as required.
- [x] I have added context for corresponding changes in documentation and [`README.md`](README.md) as needed.
- [ ] I have added new workflow CI tests for corresponding changes, ensuring codecoverage 95% or better, and these pass locally for me.
- [x] I have updated [`CHANGELOG.md`](.github/CHANGELOG.md) following the template. I recognize that the developers may revisit [`CHANGELOG.md`](.github/CHANGELOG.md) and the versioning, and create a Special Release including my changes.

### CODE REVIEW

**Comment by soosub** [comment]
Another thing I'm curious about is why the z- and y-axis are flipped in the current implementation. I guess this was done after some discussion but it does not make immediate sense to (a novel user like) me 🤔

**Comment by soosub** [comment]
TODO: Just found out that the current version is not able to show graphs partly. That is, it does not allow for slices to be displayed as you would expect. Ideally, the final version would be something analogous to matplotlib's xlim/ylim where points outside the range are ignored. 
image

**Comment by soosub** [comment]
Opened PR for review from @ilan-tz. Note, there is one thing I’m not satisfied with - the case where the axis limits don’t contain the full graph. In that case, matplotlib creates an odd image that contains edges and nodes outside the range. We could discuss what the desired solution is in that case.

**Comment by soosub** [comment]
Related SE post: https://stackoverflow.com/questions/44091229/trim-data-outside-3d-plot-in-matplotlib

**Comment by ilan-tz** [comment]
Hi @soosub ! I was close to merging this but encountered the following message:

warning

Let's investigate this before merging.

**Comment by soosub** [comment]
@ilan-tz I suspect that I know where that comes from. This some GHZ cluster state in 1D probably? If so, I'll fix it before tomorrow

**Comment by ilan-tz** [comment]
> @ilan-tz I suspect that I know where that comes from. This some GHZ cluster state in 1D probably? If so, I'll fix it before tomorrow 

Yup, a GHZ state. Comes from running the graph state tutorial.

**Comment by soosub** [comment]
@ilan-tz that should fix it! I added a check to see if the x, y and z axis limits on either side are not identical

**Comment by nariman87** [comment]
@soosub, you did not tick any items in your checklist in the description above. Any particular reason? Ideally, we want devs to confirm all.

**Comment by soosub** [comment]
> @soosub, you did not tick any items in your checklist in the description above. Any particular reason? Ideally, we want devs to confirm all.

Nope, will make sure to do that in the future. 

The only thing I did not add is new tests, I could do that tomorrow if necessary. What do you think @nariman87 ?

**Comment by nariman87** [comment]
> > @soosub, you did not tick any items in your checklist in the description above. Any particular reason? Ideally, we want devs to confirm all.
> 
> Nope, will make sure to do that in the future.
> 
> The only thing I did not add is new tests, I could do that tomorrow if necessary. What do you think @nariman87 ?

Thanks, new tests are very important, please do that with no hurries and then mark ready again.

**Pull request merged**
