### PR TITLE
Minor change in surface code example file

### PR DESCRIPTION
**Pull request by soosub**
## Context for changes

In the example file of the surface code there is an unnecessary `for` loop that can simply be removed. The new solution chooses the stabilizer to be plotted using the variable `index`, instead of requiring "consecutive indices". This is a bit neater as it removes both a `for` loop _and_ possible confusion 😉

### CODE REVIEW

**Comment by nariman87** [comment]
@soosub, great PR. Please make sure all checks are passing and the origin is synced with the latest `main`.

**Comment by soosub** [comment]
@nariman87 I synced it with main and resolved the formatting issue in the file I changed. The failing CodeFactor checks are from the `tutorials` folder (i.e. I'm innocent 👼🏼). I'll open it up for review, cheers!

**Review by ilan-tz — CHANGES_REQUESTED** [review]
Thanks! Good thinking on removing the indexing and the loop. However, we may want to give the user the option to draw a single stabilizer, or some subset of them. Could you please add a few lines to implement this?

**Comment by soosub** [comment]
@ilan-tz this should work - what do you think?

**Comment by soosub** [comment]
I am not sure why the test started to fail in the [7eba306]](https://github.com/XanaduAI/flamingpy/pull/44/commits/7eba3060cfa7245bed7816f0dc678b37c2044ab7) commit, but it's not related to the file I changed. Were the test parameters/thresholds changed? Anyway, let me know if I still need to fix something @ilan-tz

**Comment by soosub** [comment]
Woops, I accidentally kept on working when addressing the stuff in PR #33. I'll make sure I'll cherry pick the commits into the corresponding branch and then revert the commits in this branch

**Comment by soosub** [comment]
Note to self - I messed up with git. All commits after [7eba306](https://github.com/XanaduAI/flamingpy/pull/44/commits/7eba3060cfa7245bed7816f0dc678b37c2044ab7) were accidentally done on this branch and should be discarded.

**Pull request merged**
